server:
  servlet:
    context-path: /book-gather
  port: 20000

#日志配置
logging:
  config: classpath:logback.xml
  level:
    cn.stt.book.reader.mapper: debug

mybatis:
  mapper-locations: classpath:sqlmap/*.xml
  type-aliases-package: cn.stt.book.reader.entity
  configuration:
    map-underscore-to-camel-case: true

spring:
  application:
    name: book-gather
  profiles:
      active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      allow-pool-suspension: true
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  cache:
      type: redis
  redis:
    database: 0
    timeout: 100000
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1
        min-idle: 0
    password: y#tt88EE
  jackson:
    serialization:
      write-dates-as-timestamps: true

jedis: true


---
# 本地环境
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://172.25.242.115:3306/cnxl_znjk?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: znjk
    password: znjk@WS3ed
  redis:
    host: 172.25.242.115


---
# 服务器测试环境
spring:
  profiles: test
  datasource:
    url: jdbc:mysql://10.0.50.161:3306/cnxl_znjk?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: znjk
    password: znjk@WS3ed
  redis:
    host: 10.0.50.161


